// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadingService.Data;

#nullable disable

namespace ReadingService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128152403_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReadingService.Models.MonthlyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<string>("ElectricImage")
                        .HasColumnType("longtext");

                    b.Property<int>("ElectricNew")
                        .HasColumnType("int");

                    b.Property<int>("ElectricOld")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WaterImage")
                        .HasColumnType("longtext");

                    b.Property<int>("WaterNew")
                        .HasColumnType("int");

                    b.Property<int>("WaterOld")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("MonthlyReadings");
                });

            modelBuilder.Entity("ReadingService.Models.ReadingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReadingCycles");
                });

            modelBuilder.Entity("ReadingService.Models.MonthlyReading", b =>
                {
                    b.HasOne("ReadingService.Models.ReadingCycle", "Cycle")
                        .WithMany("MonthlyReadings")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("ReadingService.Models.ReadingCycle", b =>
                {
                    b.Navigation("MonthlyReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
