// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadingService.Data;

#nullable disable

namespace ReadingService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReadingService.Models.MonthlyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricNew")
                        .HasColumnType("int");

                    b.Property<int?>("ElectricOld")
                        .HasColumnType("int");

                    b.Property<string>("ElectricPhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TenantContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WaterNew")
                        .HasColumnType("int");

                    b.Property<int?>("WaterOld")
                        .HasColumnType("int");

                    b.Property<string>("WaterPhotoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.ToTable("MonthlyReadings");
                });

            modelBuilder.Entity("ReadingService.Models.ReadingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CycleMonth")
                        .HasColumnType("int");

                    b.Property<int>("CycleYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ReadingCycles");
                });

            modelBuilder.Entity("ReadingService.Models.MonthlyReading", b =>
                {
                    b.HasOne("ReadingService.Models.ReadingCycle", "ReadingCycle")
                        .WithOne("MonthlyReading")
                        .HasForeignKey("ReadingService.Models.MonthlyReading", "CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingCycle");
                });

            modelBuilder.Entity("ReadingService.Models.ReadingCycle", b =>
                {
                    b.Navigation("MonthlyReading");
                });
#pragma warning restore 612, 618
        }
    }
}
